const Routes = {
	LOADING: 'LOADING',
	MAIN_APP: 'MAIN_APP',
	INTRO: 'INTRO',
	AUTH: 'AUTH',
	CREATE_PROFILE_SCREEN: 'CREATE_PROFILE_SCREEN',
	DASHBOARD_SCREEN: 'DASHBOARD_SCREEN',
};

export default Routes;
